spring.application.name=servlet
# 스프링 부트 3.2 이후로는 `debug` 대신 `trace`로 설정해야 로그를 출력해볼 수 있다
# 운영 서버에서 이렇게 요청에 대한 정보를 다 남기면 성능 저하가 발생할 수 있다. 개발 단계에서만 사용하기!
# logging.level.org.apache.coyote.http11=trace

# Received [
# GET /hello?username=doorcs HTTP/1.1
# Host: localhost:8080
# User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:149.0) Gecko/20100101 Firefox/149.0
# Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
# Accept-Language: ko-KR,en-US;q=0.9
# Accept-Encoding: gzip, deflate, br, zstd
# Sec-GPC: 1
# Connection: keep-alive
# Upgrade-Insecure-Requests: 1
# Sec-Fetch-Dest: document
# Sec-Fetch-Mode: navigate
# Sec-Fetch-Site: none
# Sec-Fetch-User: ?1
# DNT: 1
# Priority: u=0, i
#
# ]
